# Generated by Django 2.2.12 on 2020-04-07 15:16

from django.db import migrations, models
import djongo.models.fields
import herramienta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('palabras_clave', djongo.models.fields.ArrayField(model_container=models.CharField(max_length=50))),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('palabras_clave', djongo.models.fields.ArrayField(model_container=models.CharField(max_length=50))),
                ('categorias', djongo.models.fields.ArrayField(model_container=herramienta.models.Categoria)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.CharField(max_length=100, verbose_name='Fecha creado')),
                ('id_twitter', models.CharField(max_length=100, verbose_name='id en twitter')),
                ('texto', models.CharField(max_length=300, verbose_name='Texto del tweet')),
                ('truncado', models.BooleanField(default=False, verbose_name='¿ es truncado ?')),
                ('geo', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Geolocalización')),
                ('coordenadas', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='coordenadas')),
                ('place', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Lugar')),
                ('numero_ret', models.IntegerField(default=0, verbose_name='Número de retweet')),
                ('numero_fav', models.IntegerField(default=0, verbose_name='Número de retweet')),
                ('esFavorito', models.BooleanField(default=False, verbose_name='¿ es favorito?')),
                ('esRetweet', models.BooleanField(default=False, verbose_name='¿ es favorito?')),
                ('idioma', models.CharField(max_length=3, verbose_name='Idioma')),
                ('tema', models.CharField(max_length=50, verbose_name='Tema')),
                ('categoría', models.CharField(max_length=50, verbose_name='Categoria')),
                ('polaridad', models.CharField(max_length=50, verbose_name='Polaridad')),
                ('numero_Polaridad', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Número de polaridad')),
                ('busqueda', models.CharField(max_length=50, verbose_name='Búsqueda utilizada')),
                ('analisis', models.CharField(max_length=50, verbose_name='Análisis utilizado')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
    ]
